// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-build-milestones.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_build_milestones_default = defineTool({
  name: "list_build_milestones",
  title: "List Build List milestones",
  description: "List the signed-in user's Build List milestones (active tasks) with completion status. Use this to see what fatherhood-prep tasks are active or completed.",
  inputSchema: {
    only_incomplete: z.boolean().optional().describe("If true, return only milestones not yet completed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_incomplete }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const db = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: milestones, error: mErr } = await db.from("build_milestones").select("id, title, why_it_matters, phase, priority, recommended_week, required, est_minutes, is_active").eq("is_active", true).order("recommended_week", { ascending: true });
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const { data: completions } = await db.from("user_milestones").select("milestone_id, completed_at").eq("user_id", userId);
    const completedMap = new Map((completions ?? []).map((c) => [c.milestone_id, c.completed_at]));
    let rows = (milestones ?? []).map((m) => ({
      ...m,
      completed: completedMap.has(m.id),
      completed_at: completedMap.get(m.id) ?? null
    }));
    if (only_incomplete) rows = rows.filter((r) => !r.completed);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { milestones: rows }
    };
  }
});

// src/lib/mcp/tools/get-readiness-summary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_readiness_summary_default = defineTool2({
  name: "get_readiness_summary",
  title: "Get Readiness score",
  description: "Return the signed-in user's most recent Father Readiness assessment: total score, category scores, and weakest category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const db = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const { data: assessment, error } = await db.from("assessments").select("id, total_score, weakest_category, completed_at").eq("user_id", userId).order("completed_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!assessment) {
      return {
        content: [{ type: "text", text: "No assessment completed yet." }],
        structuredContent: { assessment: null }
      };
    }
    const { data: categories } = await db.from("assessment_category_scores").select("category, score").eq("assessment_id", assessment.id);
    const result = { ...assessment, categories: categories ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { assessment: result }
    };
  }
});

// src/lib/mcp/tools/get-current-program-week.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_current_program_week_default = defineTool3({
  name: "get_current_program_week",
  title: "Get current training program week",
  description: "Return the signed-in user's active live-schedule training program (Forge or Rebuild) and the currently unlocked week.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const db = supabaseForUser3(ctx);
    const userId = ctx.getUserId();
    const { data: assignment, error } = await db.from("program_assignments").select("id, program_id, status, start_date, member_timezone, programs(name, uses_live_schedule)").eq("user_id", userId).eq("is_active", true).order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!assignment) {
      return { content: [{ type: "text", text: "No active program." }], structuredContent: { assignment: null } };
    }
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const { data: weeks } = await db.from("scheduled_program_weeks").select("id, week_number, unlock_at, publish_status").eq("assignment_id", assignment.id).lte("unlock_at", nowIso).order("week_number", { ascending: false }).limit(1);
    const current = weeks?.[0] ?? null;
    return {
      content: [
        { type: "text", text: JSON.stringify({ assignment, current_week: current }, null, 2) }
      ],
      structuredContent: { assignment, current_week: current }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "evnsxprzzczwhoobobdw";
var mcp_default = defineMcp({
  name: "m2f-mcp",
  title: "M2F \u2014 Man to Father",
  version: "0.1.0",
  instructions: "Tools for the Man-to-Father app. Read the signed-in user's Build List milestones, Father Readiness score, and current training program week (Forge/Rebuild).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_build_milestones_default, get_readiness_summary_default, get_current_program_week_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
